### ISSUE TITLE
I keep getting ARCHIVE FAILED error 65

### ISSUE THREAD

**Issue by AndrewVos** [vfrascello/XCode-Deploy#13]
Has anyone seen this? I'm using the default output project from PWABuilder.

```
  Executing: `xcodebuild -workspace /Users/runner/work/color-ios/color-ios/Color.xcworkspace -scheme Color -destination generic/platform=iOS -configuration Release -sdk iphoneos -derivedDataPath /Users/runner/work/color-ios/color-ios/build/derivedData -archivePath Color.xcarchive archive | xcpretty --color`
Running xcodebuild
  ** ARCHIVE FAILED **
  Error: Xcodebuild action failed (65)!
```

**Comment by observableobject** [comment]
This could happen for literally hundreds of reasons. Error 65 basically
means Xcode build failed. My recommendation is run the command you see
below on your local machine and see if it passes, adding a verbose tag and
see where specifically it errors.
